### ISSUE TITLE
请教，这三行me看懂

### ISSUE THREAD

**Issue by lluck42** [wanghaoxi3000/gin-rtsp#14]
reflush := make(chan int) # make 不应该写在函数外层作为全局变量么。。
if cmd, stdin, err := runFFMPEG(service.URL, processCh); err != nil {
	return serializer.Err(400, err.Error(), err)
} else {
	go keepFFMPEG(cmd, stdin, &reflush, processCh)
}

**Comment by wanghaoxi3000** [comment]
每个不同的rtsp视频流都对应了一个不同的的chan，全局的如何对每个视频流进行单独的控制呢

**Comment by lluck42** [comment]
用map[rtsp url] = chan 不用直接 delete 掉， 咋样

**Comment by wanghaoxi3000** [comment]
不太明白这个意思，是说所有的url共用一个chan吗？
